version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/repos
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: sudo npm install pm2
      - run:
          command: sudo npm run lint
      - run:
          command: npx pm2 start picon.js
      - run:
          command: npm test
