version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/repos
    steps:
      - checkout
      #- run:
      #    command: sudo apt install ffmpeg
      - run:
          command: npm install
      - run:
          command: npm start
      - run:
          command: npm test
